[tool.poetry]
name = "tistory-django-jsonform"
version = "1.0.0"
description = ""
authors = ["gnam"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "5.0"
django-jsonform = "^2.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
